---
title: "Modeling Dyadic Interactions"
author: "S.W. Berkhout"
output: html_document
---

```{r echo = FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r}
library("dynr")
library("mgcv")
library("tsDyn")
source("plotFunctions.R")
```

```{r}
load("QID_exampleData.RData")
id <- 23
dyad <- QID_exampleData[QID_exampleData$couple == id, ]
x <- dyad$dial[dyad$person == id]
y <- dyad$dial[dyad$person == id+500]
df <- data.frame(x = x, y = y)
df <- na.omit(df)
dat <- ts(df)
rawData <- dynr.data(dat)
```

```{r}
datTS <- dyad[, c("person", "time", "dial")]
names(datTS) <- c("partner", "t", "behavior")
myTS(datTS)

```


### VAR
```{r cache=T}
measVAR <- prep.measurement(
  values.load=matrix(c(1, 0,
                       0, 1), ncol = 2, byrow = T), 
  params.load=matrix(rep("fixed", 4), ncol = 2),
  state.names=c("x","y"),
  obs.names=c("x","y")
)

formVAR = list(
  list(x ~ a_x + phi_x*x + beta_x*y,
       y ~ a_y + phi_y*y + beta_y*x)
)

dynmVAR  <- prep.formulaDynamics(formula=formVAR,
                              startval=c(a_x = .01, a_y = .01,
                                         phi_x = .01, beta_x = .01, 
                                         phi_y = .01, beta_y = .01), 
                              isContinuousTime=FALSE)

initVAR <- prep.initial(
  values.inistate=c(.01, .01),
  params.inistate=c('mu_x', 'mu_y'),
  values.inicov=matrix(c(1, .01,
                         .01,1),byrow=T,ncol=2),
  params.inicov=matrix(c("v_11","c_21",
                         "c_21","v_22"),byrow=T,ncol=2))

noiseVAR <- prep.noise(
  values.latent=matrix(c(1,.01,
                         .01,1),byrow=T,ncol=2), 
  params.latent=matrix(c("v_x","c_xy",
                         "c_xy","v_y"),byrow=T,ncol=2), 
  values.observed=diag(rep(0,2)), 
  params.observed=diag(c('fixed','fixed'),2))

modVAR <- dynr.model(dynamics=dynmVAR, measurement=measVAR,
                    noise=noiseVAR, initial=initVAR, data=rawData)
resVAR <- dynr.cook(modVAR,debug_flag=TRUE,verbose = FALSE)
```

```{r}
summary(resVAR)
```

### Latent VAR
```{r cache=T}
measLVAR <- prep.measurement(
  values.load=matrix(c(1, 0,
                       0, 1), ncol = 2, byrow = T), 
  params.load=matrix(rep("fixed", 4), ncol = 2),
  state.names=c("s.x","s.y"),
  obs.names=c("x","y")
)

formLVAR = list(
  s.x ~ a_x + phi_x*s.x + beta_x*s.y,
  s.y ~ a_y + phi_y*s.y + beta_y*s.x)

dynmLVAR  <- prep.formulaDynamics(formula=formLVAR,
                              startval=c(a_x = .01, a_y = .01,
                                         phi_x = .01, beta_x = .01, 
                                         phi_y = .01, beta_y = .01), 
                              isContinuousTime=FALSE)

initLVAR <- prep.initial(
  values.inistate=c(0, 0),
  params.inistate=c('fixed', 'fixed'),
  values.inicov=matrix(c(1,0,
                         0,1),byrow=T,ncol=2),
  params.inicov=matrix(c("fixed","fixed",
                         "fixed","fixed"),byrow=T,ncol=2))

noiseLVAR <- prep.noise(
  values.latent=matrix(c(1,.01,
                         .01,1),byrow=T,ncol=2), 
  params.latent=matrix(c("v_x","c_xy",
                         "c_xy","v_y"),byrow=T,ncol=2), 
  values.observed=diag(rep(0,2)), 
  params.observed=diag(c('e_x','e_y'),2))

modLVAR <- dynr.model(dynamics=dynmLVAR, measurement=measLVAR,
                    noise=noiseLVAR, initial=initLVAR, data=rawData)
resLVAR <- dynr.cook(modLVAR,debug_flag=TRUE,verbose = FALSE)
```

```{r}
summary(resLVAR)
```

### TV-VAR
```{r cache=T}
df$x_l <- c(NA, df$x[-length(df$x)])
df$y_l <- c(NA, df$y[-length(df$y)])
tt <- 1:nrow(df)

k <- 10

resTVVAR_y<-gam(y~s(tt,k=k)+s(tt,by=y_l,k=k)+s(tt,by=x_l,k=k),data=df)
resTVVAR_x<-gam(x~s(tt,k=k)+s(tt,by=x_l,k=k)+s(tt,by=y_l,k=k),data=df)
```

```{r}
summary(resTVVAR_y)
summary(resTVVAR_x)

myTVpars(resTVVAR_y, "y")
myTVpars(resTVVAR_x, "x")
```

### TAR
```{r cache=T}
resTAR_y <- TVAR(dat, lag = 1, mTh = 1)
resTAR_x <- TVAR(dat, lag = 1, mTh = 2)
```

```{r}
summary(resTAR_y)
summary(resTAR_x)
```

```{r}
datTAR <- dyad[, c("person", "time", "dial")]
names(datTAR) <- c("partner", "t", "behavior")
# x = 23, y = 523
datTAR$regime <- c(resTAR_x$model.specific$regime, resTAR_y$model.specific$regime)

myTS(datTAR, regime = T)
```


### HMM
```{r cache=T}
measHMM <- prep.measurement(
  values.load=rep(list(matrix(c(1, 0, 0, 1), ncol = 2, byrow = T)), 2),
  obs.names = c('x', 'y'),
  state.names=c('x', 'y')
)

noiseHMM <- prep.noise(
  values.latent=list(matrix(c(1, .01, .01, 1), ncol = 2, byrow = T)),
  params.latent=list(matrix(c("v_x","c_xy",
                              "c_xy","v_y"),byrow=T,ncol=2)),
  values.observed=matrix(c(0, 0, 0, 0), ncol = 2, byrow = T),
  params.observed=matrix(rep('fixed', 4), ncol = 2, byrow = T))

dynmHMM <- prep.matrixDynamics(
  values.dyn=list(matrix(c(0, 0, 0, 0), ncol = 2, byrow = T)),
  params.dyn=list(matrix(c('fixed', 'fixed', 'fixed', 'fixed'), ncol = 2, byrow = T)),
  values.int = list(matrix(c(.01, .01), ncol = 1, byrow = T), matrix(c(.01, .01), ncol = 1, byrow = T)),
  params.int = list(matrix(c('mu_x1', 'mu_y1'), ncol = 1, byrow = T), matrix(c('mu_x2', 'mu_y2'), ncol = 1, byrow = T)),
  isContinuousTime=FALSE)

regHMM <- prep.regimes(
  values=matrix(0, 2, 2),
  params=matrix(c('p11', 'p21', 'fixed', 'fixed'), 2, 2))

initHMM <- prep.initial(
  values.inistate=matrix(c(0, 0), ncol = 1, byrow = T),
  params.inistate=matrix(rep('fixed', 2), ncol = 1, byrow = T),
  values.inicov=matrix(c(1, .01,
                         .01,1),byrow=T,ncol=2),
  params.inicov=matrix(c("v_11","c_21",
                         "c_21","v_22"),byrow=T,ncol=2),
  values.regimep=c(1, 0),
  params.regimep=c('fixed', 'fixed'))

modHMM <- dynr.model(dynamics=dynmHMM, measurement=measHMM, noise=noiseHMM, initial=initHMM, regimes=regHMM, data=rawData)

resHMM <- dynr.cook(modHMM,debug_flag=TRUE,verbose = FALSE)
```

```{r fig.height=6}
summary(resHMM)
datHMM <- dyad[, c("person", "time", "dial")]
names(datHMM) <- c("partner", "t", "behavior")
datHMM$regime <- apply(resHMM@pr_t_given_T, 2, which.max)
myTS(datHMM, regime = T)
```

### MS-VAR
```{r cache=T}
measMSVAR <- prep.measurement(
  values.load=rep(list(matrix(c(1, 0, 0, 1), ncol = 2, byrow = T)), 2),
  obs.names = c('x', 'y'),
  state.names=c('x', 'y')
)

noiseMSVAR <- prep.noise(
  values.latent=list(matrix(c(1, .01, .01, 1), ncol = 2, byrow = T),
                     matrix(c(1, .01, .01, 1), ncol = 2, byrow = T)),
  params.latent=list(matrix(c("v_x1","c_xy1",
                              "c_xy1","v_y1"),byrow=T,ncol=2),
                     matrix(c("v_x2","c_xy2",
                              "c_xy2","v_y2"),byrow=T,ncol=2)),
  values.observed=matrix(c(0, 0, 0, 0), ncol = 2, byrow = T),
  params.observed=matrix(rep('fixed', 4), ncol = 2, byrow = T))

dynmMSVAR <- prep.matrixDynamics(
  values.dyn=list(matrix(c(.01, .01, .01, .01), ncol = 2, byrow = T), 
                  matrix(c(.01, .01, .01, .01), ncol = 2, byrow = T)),
  params.dyn=list(matrix(c('phi_x1', 'beta_x1', 'beta_y1', 'phi_y1'), ncol = 2, byrow = T), 
                  matrix(c('phi_x2', 'beta_x2', 'beta_y2', 'phi_y2'), ncol = 2, byrow = T)),
  values.int = list(matrix(c(.01, .01), ncol = 1, byrow = T), 
                    matrix(c(.01, .01), ncol = 1, byrow = T)),
  params.int = list(matrix(c('a_x1', 'a_y1'), ncol = 1, byrow = T), 
                    matrix(c('a_x2', 'a_y2'), ncol = 1, byrow = T)),
  isContinuousTime=FALSE)

regMSVAR <- prep.regimes(
  values=matrix(0, 2, 2),
  params=matrix(c('p11', 'p21', 'fixed', 'fixed'), 2, 2))

initMSVAR <- prep.initial(
  values.inistate=matrix(c(.01, .01), ncol = 1, byrow = T),
  params.inistate=matrix(rep('fixed', 2), ncol = 1, byrow = T),
  values.inicov=matrix(c(1, 0, 0, 1),byrow=T,ncol=2),
  params.inicov=matrix(c("fixed","fixed",
                         "fixed","fixed"),byrow=T,ncol=2),
  values.regimep=c(1, 0),
  params.regimep=c('fixed', 'fixed'))

modMSVAR <- dynr.model(dynamics=dynmMSVAR, measurement=measMSVAR, 
                       noise=noiseMSVAR,
                       initial=initMSVAR, regimes=regMSVAR, 
                       data=rawData)
resMSVAR <- dynr.cook(modMSVAR, verbose = FALSE)
```

```{r fig.height=6}
summary(resMSVAR)
datMSVAR <- dyad[, c("person", "time", "dial")]
names(datMSVAR) <- c("partner", "t", "behavior")
datMSVAR$regime <- apply(resMSVAR@pr_t_given_T, 2, which.max)
myTS(datMSVAR, regime = T)
```